name: Release

on:
  push:
    branches:
      - main

jobs:
  audit:
    name: Audit dependencies
    runs-on: rows-fe-default
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: Audit dependencies
        run: npm audit --production --audit-level=high

  static-analysis:
    name: Static analysis
    runs-on: rows-fe-default
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-node

      - uses: ./.github/actions/install-dependencies
        with:
          node-auth-token: ${{ secrets.NODE_AUTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Linting JS/TS
        run: npm run lint

      - name: Type checking
        run: npm run check-types

  create-release:
    name: Create Release
    needs: [static-analysis, audit]
    runs-on: rows-fe-default
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Default GITHUB_TOKEN has no permissions to push to locked branches, so we don't
          # persist credentials and use the NODE_AUTH_TOKEN personal access token instead
          persist-credentials: false

      - uses: ./.github/actions/setup-node
        with:
          node-version: 20

      # Install node dependencies
      # Hack: must be made before semantic-release/npm runs, otherwise it will try to npm install
      # without proper `.npmrc` and fail to install @rows/matisse. The `ignore-scripts` is needed
      # to avoid installing husky, which is messing with semantic-release's commits.
      - name: Install
        run: npm ci --no-audit --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      # Semantic release
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
          branch: main
        env:
          # Use NODE_AUTH_TOKEN as GITHUB_TOKEN to allow pushing commits into locked "master" branch
          GITHUB_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}


      - name: Build Chrome extension artifact
        if: steps.semantic_release_step.outputs.new_release_published == 'true'
        run: |
          npm run build
          cd dist
          zip -r ../chrome-extension-${{ github.sha }}.zip *

      - name: Archive chrome-extension artifact
        uses: actions/upload-artifact@v2
        with:
          name: chrome-extension-${{ github.sha }}
          path: chrome-extension-${{ github.sha }}.zip
